name: covid_tracker
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  charts_flutter: ^0.12.0
  shared_preferences: ^2.0.8
  http: ^0.13.4
  shimmer: ^2.0.0
  timeago: ^3.1.0
  equatable: ^2.0.3
  flutter_bloc: ^8.0.0
  internet_connection_checker: ^0.0.1+3
  fpdart: ^0.0.12
  get_it: ^7.2.0


  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  build_runner: ^2.1.5
  bloc_test: ^9.0.0
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
